### Difference and Inverted Difference

In [10]:
import numpy as np
from IPython.display import display as disp

#difference
x = np.array([1, 2, 4, 7, 0])
x_diff = np.diff(x,1)
disp(x_diff)

#invereted difference
x_invert=np.r_[x[0], x_diff].cumsum()
disp(x_invert)

array([ 1,  2,  3, -7])

array([1, 2, 4, 7, 0])

In [9]:
import numpy as np
from IPython.display import display as disp

#difference
x = np.array([1, 2, 4, 7, 0])
x_diff = np.diff(x,2)
disp(x_diff)

array([  1,   1, -10])

In [ ]:
    result = []
    for index in range(len(data) - sequence_length):
        result.append(data[index: index + sequence_length])

In [ ]:
days_in_year = 365
for i in range(days_in_year, len(X)):
	value = X[i] - X[i - days_in_year]
	diff.append(value)