In [13]:
import numpy as np
from IPython.display import display

### The new numpy variable is just view from original variable

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]],float)
b=a.reshape(3,2)
b[0,0]=7
display(a)
display(b)

array([[ 7.,  2.,  3.],
       [ 4.,  5.,  6.]])

array([[ 7.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

In [18]:
a = np.array([1, 2, 3])
b=a.reshape(a.shape[0],1)
display(a)
display(b)

array([1, 2, 3])

array([[1],
       [2],
       [3]])

In [19]:
whos

Variable   Type        Data/Info
--------------------------------
a          ndarray     3: 3 elems, type `int64`, 24 bytes
b          ndarray     3x1: 3 elems, type `int64`, 24 bytes
display    function    <function display at 0x110cde620>
np         module      <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>


In [ ]:
X.reshape(X.shape[0], 1, X.shape[1])

### Difference and Inverted Difference (t and t+1)

In [10]:
import numpy as np
from IPython.display import display as disp

#difference
x = np.array([1, 2, 4, 7, 0])
x_diff = np.diff(x,1)
disp(x_diff)

#invereted difference
x_invert=np.r_[x[0], x_diff].cumsum()
disp(x_invert)

array([ 1,  2,  3, -7])

array([1, 2, 4, 7, 0])

### Difference and Inverted Difference (t and t+lookback)

In [21]:
import numpy as np
from IPython.display import display as disp

#difference
x = np.array([1, 2, 4, 7, 0])

lookback=3
result=[]
for i in range(len(x)-lookback):
    result.append(x[i+lookback] - x[i])
    
disp(result)
   
#invereted difference
result_invert=[]
for i in range(len(x)-lookback):
    result_invert.append(x[i+lookback])
    
disp(result_invert)

[6, -2]

[7, 0]