In [7]:
import numpy as np
from numpy.random import randint 
from numpy.random import random 
from IPython.display import display

### The new numpy variable is just view from original variable

In [66]:
a = np.array([[1, 2, 3], [4, 5, 6]],float)
b=a.reshape(3,2)
a[0,0]=7
display(a)
display(b)


array([[ 7.,  2.,  3.],
       [ 4.,  5.,  6.]])

array([[ 7.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

In [2]:
a = np.array([1, 2, 3])
b=a.reshape(a.shape[0],1)
c=a.reshape(a.shape[0],1,1)
display(a)
display(b)
display(c)
display(a.shape)
display(b.shape)
display(c.shape)

array([1, 2, 3])

array([[1],
       [2],
       [3]])

array([[[1]],

       [[2]],

       [[3]]])

(3,)

(3, 1)

(3, 1, 1)

### Difference and Inverted Difference (t and t+1)

In [10]:
import numpy as np
from IPython.display import display as disp

#difference
x = np.array([1, 2, 4, 7, 0])
x_diff = np.diff(x,1)
disp(x_diff)

#invereted difference
x_invert=np.r_[x[0], x_diff].cumsum()
disp(x_invert)

array([ 1,  2,  3, -7])

array([1, 2, 4, 7, 0])

### Difference and Inverted Difference (t and t+lookback)

In [21]:
import numpy as np
from IPython.display import display as disp

#difference
x = np.array([1, 2, 4, 7, 0])

lookback=3
result=[]
for i in range(len(x)-lookback):
    result.append(x[i+lookback] - x[i])
    
disp(result)
   
#invereted difference
result_invert=[]
for i in range(len(x)-lookback):
    result_invert.append(x[i+lookback])
    
disp(result_invert)

[6, -2]

[7, 0]

### Ravel is a new view of original view, Flatten is a new copy

change in a will change in b array, but c didn't change

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
b=a.ravel()
c=a.flatten()
a[0,0]=9

display(a)
display(b)
display(c)

array([[ 9.,  2.,  3.],
       [ 4.,  5.,  6.]])

array([ 9.,  2.,  3.,  4.,  5.,  6.])

array([ 1.,  2.,  3.,  4.,  5.,  6.])

### Row Append and Column Append

In [100]:
a=randint(5,size=(3,1))
b=randint(5,size=(3,1))
print ("variable a:")
print(a)
print ("variable b:")
print(b)
c=np.r_[a,b]
print("Row Append")
print(c)
d=np.c_[a,b]
print("Column Append")
print(d)

variable a:
[[4]
 [2]
 [0]]
variable b:
[[0]
 [2]
 [2]]
Row Append
[[4]
 [2]
 [0]
 [0]
 [2]
 [2]]
Column Append
[[4 0]
 [2 2]
 [0 2]]


### Multiplication

In [126]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
print (a)
print (b)
print (a*b)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]


In [146]:
temp = np.random.randint(1,10, 10)
print ("original array")
print (temp)
print ("original array ID")
print (id(temp))
print ("Descending Order array")
temp[::-1].sort()
print(temp)
print ("Descending Order array ID")
print(id(temp))
print ("Ascending Order array")
temp.sort()
print(temp)
print ("Ascending Order array ID")
print(id(temp))
temp1=temp.reshape(5,2).copy
print(temp)
print(id(temp))
print (np.may_share_memory(temp, temp1))

original array
[3 9 1 2 7 2 5 1 2 9]
original array ID
74323912
Descending Order array
[9 9 7 5 3 2 2 2 1 1]
Descending Order array ID
74323912
Ascending Order array
[1 1 2 2 2 3 5 7 9 9]
Ascending Order array ID
74323912
[1 1 2 2 2 3 5 7 9 9]
74323912
True
